name: Generate GitHub Animations

on:
  schedule:
    # Runs every 12 hours
    - cron: "0 */12 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  animations:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Generate your custom contribution dot
      - name: Generate Contribution Dot
        env:
          GH_USERNAME: Ayushverma1238
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          node generate-dot.js

      # Generate GitHub Snake
      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Ayushverma1238
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Prevent Jekyll processing
      - name: Create .nojekyll
        run: touch dist/.nojekyll

      # Deploy all generated files to the output branch
      - name: Deploy to Output Branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: dist
          force_orphan: true
